version: "3.3"

services:
  caddy:
    # see https://github.com/lucaslorentz/caddy-docker-proxy
    restart: unless-stopped
    image: "lucaslorentz/caddy-docker-proxy:${CADDY_IMAGE_TAG:-2.7-alpine}"
    container_name: "traefik"
    environment:
      - "CADDY_INGRESS_NETWORKS=${DOCKER_NETWORK:-web}"
    ports:
      - "80:80"
      - "443:443"
      - "${CADDY_ADMIN_PORT-2019}:${CADDY_ADMIN_PORT-2019}"
    volumes:
      - "./.caddy:/data"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      # disable the admin api unless the port is requested
      # it should not be public since it allows messing with the config
      caddy.admin: ":${CADDY_ADMIN_PORT-off}"
      caddy.metrics: "/${CADDY_METRICS_PATH-metrics} :${CADDY_METRICS_PORT-2019}"
      caddy.log.level: "${CADDY_LOG_LEVEL:-info}"
    logging:
      driver: ${DOCKER_LOG_DRIVER:-journald}
networks:
  default:
    external:
      name: "${DOCKER_NETWORK:-web}"
