version: "3.3"

services:
  app:
    restart: unless-stopped
    image: "${IMAGE_NAME}"
    env_file:
      - .env
    container_name: "${CONTAINER_NAME}"
    command: "${CONTAINER_COMMAND}"
    labels:
      caddy: "${DOMAIN}"
      caddy.reverse_proxy: "{{ upstreams $CONTAINER_PORT }}"
      # iterate over defined port map to get number from definition e.g. 8000/tcp
      # caddy.reverse_proxy: |
      #   {{ range $port, $_ := .Config.ExposedPorts }}{{ upstreams (index (split $port "/") 0 ) }} {{ end }}
    logging:
      driver: ${DOCKER_LOG_DRIVER:-json-file}
    pull_policy: always
networks:
  default:
    external:
      name: "${DOCKER_NETWORK:-web}"
